apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-service
spec:
  selector:
    matchLabels:
      app: my-app-service
  template:
    metadata:
      labels:
        app: my-app-service
    spec:
      containers:
        - name: my-app-service
          image: bhuvidh/express-app
          env:
            - name: PORT
              value: "5000"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  # labels:
  #   provider: protectonce
spec:
  type: LoadBalancer
  selector:
    app: my-app-service
  ports:
    - name: my-app-service
      port: 5000
      targetPort: 5000